/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Budget {
  'id' : RecordId,
  'month' : bigint,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'year' : bigint,
  'updatedAt' : Timestamp,
  'category' : [] | [Category],
  'amount' : bigint,
}
export interface BudgetWithSpending {
  'spent' : bigint,
  'remaining' : bigint,
  'budget' : Budget,
}
export type Category = { 'healthcare' : null } |
  { 'salary' : null } |
  { 'entertainment' : null } |
  { 'food' : null } |
  { 'travel' : null } |
  { 'rent' : null } |
  { 'education' : null } |
  { 'others' : null } |
  { 'shopping' : null };
export interface CreateTransactionInput {
  'date' : Timestamp,
  'description' : string,
  'category' : Category,
  'txType' : TransactionType,
  'amount' : bigint,
}
export interface DashboardSummary {
  'totalIncome' : bigint,
  'totalExpenses' : bigint,
  'totalBalance' : bigint,
  'transactionCount' : bigint,
}
export type RecordId = bigint;
export interface SetBudgetInput {
  'month' : bigint,
  'year' : bigint,
  'category' : [] | [Category],
  'amount' : bigint,
}
export type Timestamp = bigint;
export interface Transaction {
  'id' : RecordId,
  'userId' : UserId,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'category' : Category,
  'txType' : TransactionType,
  'amount' : bigint,
}
export type TransactionType = { 'expense' : null } |
  { 'income' : null };
export interface UpdateTransactionInput {
  'id' : RecordId,
  'date' : Timestamp,
  'description' : string,
  'category' : Category,
  'txType' : TransactionType,
  'amount' : bigint,
}
export interface UpsertUserInput { 'username' : string, 'email' : string }
export interface User {
  'id' : UserId,
  'username' : string,
  'createdAt' : Timestamp,
  'email' : string,
}
export type UserId = string;
export interface _SERVICE {
  'createTransaction' : ActorMethod<[CreateTransactionInput], Transaction>,
  'deleteBudget' : ActorMethod<[bigint], undefined>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'getBudgets' : ActorMethod<[], Array<BudgetWithSpending>>,
  'getDashboardSummary' : ActorMethod<[], DashboardSummary>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getTransactionsByCategory' : ActorMethod<[Category], Array<Transaction>>,
  'getTransactionsByMonth' : ActorMethod<[bigint, bigint], Array<Transaction>>,
  'getUser' : ActorMethod<[], [] | [User]>,
  'setBudget' : ActorMethod<[SetBudgetInput], Budget>,
  'updateTransaction' : ActorMethod<[UpdateTransactionInput], Transaction>,
  'upsertUser' : ActorMethod<[UpsertUserInput], User>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];