/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const Category = IDL.Variant({
  'healthcare' : IDL.Null,
  'salary' : IDL.Null,
  'entertainment' : IDL.Null,
  'food' : IDL.Null,
  'travel' : IDL.Null,
  'rent' : IDL.Null,
  'education' : IDL.Null,
  'others' : IDL.Null,
  'shopping' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'expense' : IDL.Null,
  'income' : IDL.Null,
});
export const CreateTransactionInput = IDL.Record({
  'date' : Timestamp,
  'description' : IDL.Text,
  'category' : Category,
  'txType' : TransactionType,
  'amount' : IDL.Nat,
});
export const RecordId = IDL.Nat;
export const UserId = IDL.Text;
export const Transaction = IDL.Record({
  'id' : RecordId,
  'userId' : UserId,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'category' : Category,
  'txType' : TransactionType,
  'amount' : IDL.Nat,
});
export const Budget = IDL.Record({
  'id' : RecordId,
  'month' : IDL.Nat,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'year' : IDL.Nat,
  'updatedAt' : Timestamp,
  'category' : IDL.Opt(Category),
  'amount' : IDL.Nat,
});
export const BudgetWithSpending = IDL.Record({
  'spent' : IDL.Nat,
  'remaining' : IDL.Int,
  'budget' : Budget,
});
export const DashboardSummary = IDL.Record({
  'totalIncome' : IDL.Nat,
  'totalExpenses' : IDL.Nat,
  'totalBalance' : IDL.Int,
  'transactionCount' : IDL.Nat,
});
export const User = IDL.Record({
  'id' : UserId,
  'username' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
});
export const SetBudgetInput = IDL.Record({
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'category' : IDL.Opt(Category),
  'amount' : IDL.Nat,
});
export const UpdateTransactionInput = IDL.Record({
  'id' : RecordId,
  'date' : Timestamp,
  'description' : IDL.Text,
  'category' : Category,
  'txType' : TransactionType,
  'amount' : IDL.Nat,
});
export const UpsertUserInput = IDL.Record({
  'username' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  'createTransaction' : IDL.Func([CreateTransactionInput], [Transaction], []),
  'deleteBudget' : IDL.Func([IDL.Nat], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'getBudgets' : IDL.Func([], [IDL.Vec(BudgetWithSpending)], ['query']),
  'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getTransactionsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getTransactionsByMonth' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'setBudget' : IDL.Func([SetBudgetInput], [Budget], []),
  'updateTransaction' : IDL.Func([UpdateTransactionInput], [Transaction], []),
  'upsertUser' : IDL.Func([UpsertUserInput], [User], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const Category = IDL.Variant({
    'healthcare' : IDL.Null,
    'salary' : IDL.Null,
    'entertainment' : IDL.Null,
    'food' : IDL.Null,
    'travel' : IDL.Null,
    'rent' : IDL.Null,
    'education' : IDL.Null,
    'others' : IDL.Null,
    'shopping' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'expense' : IDL.Null,
    'income' : IDL.Null,
  });
  const CreateTransactionInput = IDL.Record({
    'date' : Timestamp,
    'description' : IDL.Text,
    'category' : Category,
    'txType' : TransactionType,
    'amount' : IDL.Nat,
  });
  const RecordId = IDL.Nat;
  const UserId = IDL.Text;
  const Transaction = IDL.Record({
    'id' : RecordId,
    'userId' : UserId,
    'date' : Timestamp,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'category' : Category,
    'txType' : TransactionType,
    'amount' : IDL.Nat,
  });
  const Budget = IDL.Record({
    'id' : RecordId,
    'month' : IDL.Nat,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'year' : IDL.Nat,
    'updatedAt' : Timestamp,
    'category' : IDL.Opt(Category),
    'amount' : IDL.Nat,
  });
  const BudgetWithSpending = IDL.Record({
    'spent' : IDL.Nat,
    'remaining' : IDL.Int,
    'budget' : Budget,
  });
  const DashboardSummary = IDL.Record({
    'totalIncome' : IDL.Nat,
    'totalExpenses' : IDL.Nat,
    'totalBalance' : IDL.Int,
    'transactionCount' : IDL.Nat,
  });
  const User = IDL.Record({
    'id' : UserId,
    'username' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
  });
  const SetBudgetInput = IDL.Record({
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'category' : IDL.Opt(Category),
    'amount' : IDL.Nat,
  });
  const UpdateTransactionInput = IDL.Record({
    'id' : RecordId,
    'date' : Timestamp,
    'description' : IDL.Text,
    'category' : Category,
    'txType' : TransactionType,
    'amount' : IDL.Nat,
  });
  const UpsertUserInput = IDL.Record({
    'username' : IDL.Text,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    'createTransaction' : IDL.Func([CreateTransactionInput], [Transaction], []),
    'deleteBudget' : IDL.Func([IDL.Nat], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'getBudgets' : IDL.Func([], [IDL.Vec(BudgetWithSpending)], ['query']),
    'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getTransactionsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getTransactionsByMonth' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'setBudget' : IDL.Func([SetBudgetInput], [Budget], []),
    'updateTransaction' : IDL.Func([UpdateTransactionInput], [Transaction], []),
    'upsertUser' : IDL.Func([UpsertUserInput], [User], []),
  });
};

export const init = ({ IDL }) => { return []; };