/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface CreateTransactionInput {
    date: Timestamp;
    description: string;
    category: Category;
    txType: TransactionType;
    amount: bigint;
}
export interface SetBudgetInput {
    month: bigint;
    year: bigint;
    category?: Category;
    amount: bigint;
}
export interface User {
    id: UserId;
    username: string;
    createdAt: Timestamp;
    email: string;
}
export interface UpdateTransactionInput {
    id: RecordId;
    date: Timestamp;
    description: string;
    category: Category;
    txType: TransactionType;
    amount: bigint;
}
export interface BudgetWithSpending {
    spent: bigint;
    remaining: bigint;
    budget: Budget;
}
export interface DashboardSummary {
    totalIncome: bigint;
    totalExpenses: bigint;
    totalBalance: bigint;
    transactionCount: bigint;
}
export type RecordId = bigint;
export interface Transaction {
    id: RecordId;
    userId: UserId;
    date: Timestamp;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    category: Category;
    txType: TransactionType;
    amount: bigint;
}
export type UserId = string;
export interface UpsertUserInput {
    username: string;
    email: string;
}
export interface Budget {
    id: RecordId;
    month: bigint;
    userId: UserId;
    createdAt: Timestamp;
    year: bigint;
    updatedAt: Timestamp;
    category?: Category;
    amount: bigint;
}
export enum Category {
    healthcare = "healthcare",
    salary = "salary",
    entertainment = "entertainment",
    food = "food",
    travel = "travel",
    rent = "rent",
    education = "education",
    others = "others",
    shopping = "shopping"
}
export enum TransactionType {
    expense = "expense",
    income = "income"
}
export interface backendInterface {
    createTransaction(input: CreateTransactionInput): Promise<Transaction>;
    deleteBudget(id: bigint): Promise<void>;
    deleteTransaction(id: bigint): Promise<void>;
    getBudgets(): Promise<Array<BudgetWithSpending>>;
    getDashboardSummary(): Promise<DashboardSummary>;
    getTransactions(): Promise<Array<Transaction>>;
    getTransactionsByCategory(category: Category): Promise<Array<Transaction>>;
    getTransactionsByMonth(month: bigint, year: bigint): Promise<Array<Transaction>>;
    getUser(): Promise<User | null>;
    setBudget(input: SetBudgetInput): Promise<Budget>;
    updateTransaction(input: UpdateTransactionInput): Promise<Transaction>;
    upsertUser(input: UpsertUserInput): Promise<User>;
}
import type { Budget as _Budget, BudgetWithSpending as _BudgetWithSpending, Category as _Category, CreateTransactionInput as _CreateTransactionInput, RecordId as _RecordId, SetBudgetInput as _SetBudgetInput, Timestamp as _Timestamp, Transaction as _Transaction, TransactionType as _TransactionType, UpdateTransactionInput as _UpdateTransactionInput, User as _User, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createTransaction(arg0: CreateTransactionInput): Promise<Transaction> {
        if (this.processError) {
            try {
                const result = await this.actor.createTransaction(to_candid_CreateTransactionInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Transaction_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTransaction(to_candid_CreateTransactionInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Transaction_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteBudget(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBudget(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBudget(arg0);
            return result;
        }
    }
    async deleteTransaction(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return result;
        }
    }
    async getBudgets(): Promise<Array<BudgetWithSpending>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBudgets();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBudgets();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardSummary(): Promise<DashboardSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardSummary();
            return result;
        }
    }
    async getTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionsByCategory(arg0: Category): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionsByMonth(arg0: bigint, arg1: bigint): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByMonth(arg0, arg1);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByMonth(arg0, arg1);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async setBudget(arg0: SetBudgetInput): Promise<Budget> {
        if (this.processError) {
            try {
                const result = await this.actor.setBudget(to_candid_SetBudgetInput_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Budget_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBudget(to_candid_SetBudgetInput_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Budget_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTransaction(arg0: UpdateTransactionInput): Promise<Transaction> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransaction(to_candid_UpdateTransactionInput_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Transaction_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransaction(to_candid_UpdateTransactionInput_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Transaction_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async upsertUser(arg0: UpsertUserInput): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertUser(arg0);
            return result;
        }
    }
}
function from_candid_BudgetWithSpending_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BudgetWithSpending): BudgetWithSpending {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Budget_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Budget): Budget {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Category]): Category | null {
    return value.length === 0 ? null : from_candid_Category_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    spent: bigint;
    remaining: bigint;
    budget: _Budget;
}): {
    spent: bigint;
    remaining: bigint;
    budget: Budget;
} {
    return {
        spent: value.spent,
        remaining: value.remaining,
        budget: from_candid_Budget_n16(_uploadFile, _downloadFile, value.budget)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RecordId;
    month: bigint;
    userId: _UserId;
    createdAt: _Timestamp;
    year: bigint;
    updatedAt: _Timestamp;
    category: [] | [_Category];
    amount: bigint;
}): {
    id: RecordId;
    month: bigint;
    userId: UserId;
    createdAt: Timestamp;
    year: bigint;
    updatedAt: Timestamp;
    category?: Category;
    amount: bigint;
} {
    return {
        id: value.id,
        month: value.month,
        userId: value.userId,
        createdAt: value.createdAt,
        year: value.year,
        updatedAt: value.updatedAt,
        category: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.category)),
        amount: value.amount
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RecordId;
    userId: _UserId;
    date: _Timestamp;
    createdAt: _Timestamp;
    description: string;
    updatedAt: _Timestamp;
    category: _Category;
    txType: _TransactionType;
    amount: bigint;
}): {
    id: RecordId;
    userId: UserId;
    date: Timestamp;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    category: Category;
    txType: TransactionType;
    amount: bigint;
} {
    return {
        id: value.id,
        userId: value.userId,
        date: value.date,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        category: from_candid_Category_n9(_uploadFile, _downloadFile, value.category),
        txType: from_candid_TransactionType_n11(_uploadFile, _downloadFile, value.txType),
        amount: value.amount
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    healthcare: null;
} | {
    salary: null;
} | {
    entertainment: null;
} | {
    food: null;
} | {
    travel: null;
} | {
    rent: null;
} | {
    education: null;
} | {
    others: null;
} | {
    shopping: null;
}): Category {
    return "healthcare" in value ? Category.healthcare : "salary" in value ? Category.salary : "entertainment" in value ? Category.entertainment : "food" in value ? Category.food : "travel" in value ? Category.travel : "rent" in value ? Category.rent : "education" in value ? Category.education : "others" in value ? Category.others : "shopping" in value ? Category.shopping : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expense: null;
} | {
    income: null;
}): TransactionType {
    return "expense" in value ? TransactionType.expense : "income" in value ? TransactionType.income : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BudgetWithSpending>): Array<BudgetWithSpending> {
    return value.map((x)=>from_candid_BudgetWithSpending_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n7(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CreateTransactionInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateTransactionInput): _CreateTransactionInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_SetBudgetInput_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SetBudgetInput): _SetBudgetInput {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateTransactionInput_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateTransactionInput): _UpdateTransactionInput {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: Timestamp;
    description: string;
    category: Category;
    txType: TransactionType;
    amount: bigint;
}): {
    date: _Timestamp;
    description: string;
    category: _Category;
    txType: _TransactionType;
    amount: bigint;
} {
    return {
        date: value.date,
        description: value.description,
        category: to_candid_Category_n3(_uploadFile, _downloadFile, value.category),
        txType: to_candid_TransactionType_n5(_uploadFile, _downloadFile, value.txType),
        amount: value.amount
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    month: bigint;
    year: bigint;
    category?: Category;
    amount: bigint;
}): {
    month: bigint;
    year: bigint;
    category: [] | [_Category];
    amount: bigint;
} {
    return {
        month: value.month,
        year: value.year,
        category: value.category ? candid_some(to_candid_Category_n3(_uploadFile, _downloadFile, value.category)) : candid_none(),
        amount: value.amount
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: RecordId;
    date: Timestamp;
    description: string;
    category: Category;
    txType: TransactionType;
    amount: bigint;
}): {
    id: _RecordId;
    date: _Timestamp;
    description: string;
    category: _Category;
    txType: _TransactionType;
    amount: bigint;
} {
    return {
        id: value.id,
        date: value.date,
        description: value.description,
        category: to_candid_Category_n3(_uploadFile, _downloadFile, value.category),
        txType: to_candid_TransactionType_n5(_uploadFile, _downloadFile, value.txType),
        amount: value.amount
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    healthcare: null;
} | {
    salary: null;
} | {
    entertainment: null;
} | {
    food: null;
} | {
    travel: null;
} | {
    rent: null;
} | {
    education: null;
} | {
    others: null;
} | {
    shopping: null;
} {
    return value == Category.healthcare ? {
        healthcare: null
    } : value == Category.salary ? {
        salary: null
    } : value == Category.entertainment ? {
        entertainment: null
    } : value == Category.food ? {
        food: null
    } : value == Category.travel ? {
        travel: null
    } : value == Category.rent ? {
        rent: null
    } : value == Category.education ? {
        education: null
    } : value == Category.others ? {
        others: null
    } : value == Category.shopping ? {
        shopping: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    expense: null;
} | {
    income: null;
} {
    return value == TransactionType.expense ? {
        expense: null
    } : value == TransactionType.income ? {
        income: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
